site_name: Compound Investement Calculator
pages:
    - Calculator: calculator.md
    - Index Fund Application: index.md
theme: united
extra_javascript:
      - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - admonition
    - mdx_math